#+title: Dhl Beschwerde

Sehr geehrte Damen und Herren,

anbei moechte ich Zeugnis ablegen ueber die erschreckenden Erfahrungen, die ich mit der DHL in den vergangenen 3 Wochen gemacht habe.
Dies dient der Dokumentation und soll dazu bewegen, Ihren fatalen Kudenservice etwas aufzubessern.

Am 16.05 habe ich ein Paket erhalten, dessen Inhalt beim Versand beschaedigt wurde. Unmittelbar nach Feststellen des Schadens habe ich mich informiert und beim Kundenservice ueber die zentrale Hotline in Bonn angerufen.
Nach Schilderung der Sachlage und einem Apell, dass die beschaedigte Ware noch weiter beschaedigt wuerde, falls Sie im Paket an das Nachbearbeitungszentrum ginge, hat mich ein Mitarbeiter gebeten, die Schadensanzeige mit Bildern einzureichen.
Dies ist noch am selben Tag geschehen. Bei der Einlieferung der Schadensanzeige habe ich auch nach mehrmaliger Nachfrage keinen Beleg erhalten.

Im Verlauf der kommenden 2 Wochen habe ich dann ca. 5 Mal bei der DHL angerufen, um mich nach dem Status der Schadensanzeige zu erkundigen. Jedes Mal wurde mir gesagt, dass noch keine Informationen im System vorliegen wuerden und es wahrscheinlich noch ein paar Tage dauert. Die Telefonate haben aufgrund der Sachlage und der Wartezeit jeweils eine nicht zu vernachlaessigende Zeit in Anspruch genommen.

Am Dienstag, dem 30.05 wurde mir dann gesagt, dass die Frist abgelaufen sei. Eine Mitarbeiterin hat gar aufgelegt, waehrend ich Ihr erklaert habe, dass die Schadensanzeige bereits erfolgt sei. Nachdem ich sofort noch einmal angerufen und um einen Manager gebeten habe, konnte ich diesem noch einmal die Lage erklaeren. Dieser entschuldigte sich und beauftragte die Abholung der Sendung, auch unter Vorwarnung, dass diese Gefahr laeuft, weitere Schaeden davonzutragen. Die Abholung am naechsten Tag schlug fehl, da ich kein Versandlabel oder Aehnliches bekommen hatte und die originale Frankierung nicht mehr vorhanden war.

Erneut habe ich angerufen beim Kundenservice und nach 3! Gespraechen bin ich an einen anderen Manager gelangt, der eine erneute Abholung veranlasst hat. Obwohl ich ihm die Problematik mit dem fehlenden Label/ der fehlenden Frankierung geschildert habe, versicherte er mir, dass das Paket am naechsten Tag vom Kurier mitgenommen wuerde. Dieser wuesste darueber aufgrund der Art des Abholungsauftrags Bescheid. Natuerlich war dies nicht der Fall aus dem selben Grund wie am Tag zuvor. Er konnte das Paket aufgrund eines fehlenden Labels nicht mitnehmen.

Erneut habe ich die DHL kontaktiert und die Lage geschildert. Nach 2 Gespraechen bin ich an den Manager gelangt, der die erste Abholungg veranlasst hat. Dieser versuchte eine Loesung mit mir zu finden. Die bestand darin, das originale Label vom Versender des Paketes zu besorgen und das Paket in einer Filiale abzugeben. Im System sei hinterlegt, dass das Paket an die DHL zurueckgehen sollte zur Inspektion. Nachdem ich dies erledigt hatte am Samstag, 03.06, wurde das Paket gestern fuer mich wieder in der lokalen Postzentrale abgegeben. Daraus schliesse ich, dass es direkt von der Postzentrale, wo ich es abgegeben habe, zu mir gesendet wurde.
Die Mitarbeiterin in der Poststelle konnte mir leider auch nicht weiterhelfen also schleppte ich das Paket nach Hause und versuchte die DHL erneut zu kontaktieren -- ohne Erfolg. Die Rufnummer sei nicht vergeben. Es handelt sich dabei um genau die Rufnummer, die ich die letzen 10-15 Anrufe kontaktiert hatte, um mein Anliegen zu klaeren.

Ich moechte Sie darauf hinweisen, wie viel Zeit und Umstaende die Klaerung dieses Anliegens in Anspruch nimmt. Neben den Telefonaten, die mindesetens 30 Minuten dauern, bis die Mitarbeiter verstehen, was die Lage ist, kommt hinzu, dass ich 2 Tage lang gezwungen war, zu Hause zu sein, damit die Abholung erfolgen kann. Darueberhinaus muss ich das Paket von Filiale zu Filiae schleppen, was bei einem Gewicht von ca. 15 kg nicht gerade angenehm ist.

Ich bin schwer enttaeuscht vom Service der DHL und werde mich im Notfall gezwungen sehen, meine Rechte anwaltlich durchzusetzen. Es kann und darf nicht sein, dass sich ein Unternehmen seinen Pflichten entzieht, einfach in dem es jegliche Kommunikation verweigert und dermassen schlechte interne Ablaeuft besitzt. Der Wert, den ich von der DHL fuer die Beschaedigung des Paketes fordere ist bereits um Weiten ueberschritten durch den Aufwand und die Zeit, die ich fuer die Loesung dieses Problems geopfert habe.

Ich appeliere an Sie, eine schnelle Loesung des Problems zu finden.


Mit freundlichen Gruessen
Andreas Loehr
